---
- name: Install Helm on Jenkins slaves
  hosts: kubernetes_master
  become: yes

  tasks:
    - name: Download and install Helm binary
      ansible.builtin.shell:
        cmd: |
          curl -fsSL -o /tmp/helm.tar.gz https://get.helm.sh/helm-v3.19.0-linux-amd64.tar.gz
          tar -xzf /tmp/helm.tar.gz -C /tmp
          mv /tmp/linux-amd64/helm /usr/local/bin/helm
          chmod +x /usr/local/bin/helm
        creates: /usr/local/bin/helm
